steps:
# Check passed TAG_NAME for uniqueness
- id: check-tag
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args: 
    - -c
    - |
      set -e

      echo "Checking if tag exists: ${_IMAGE}:${TAG_NAME}"
      if gcloud artifacts docker tags list "${_IMAGE}" --format='get(TAG)' | grep -qx "${TAG_NAME}"; then
        echo "Tag ${TAG_NAME} already exists. Aborting build."
        exit 1
      else
        echo "Tag does not exist. Continuing."
      fi
# Build the valhalla container image
- id: build-image
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--build-arg'
    - 'VALHALLA_BUILDER_IMAGE={_BUILDER_IMAGE}:latest'
    - '--build-arg'
    - 'VALHALLA_UID=59998'
    - '--build-arg'
    - 'VALHALLA_GID=59998'
    - '-t'
    - '${_IMAGE}:${TAG_NAME}'
    - '-t'
    - '${_IMAGE}:latest'
    - '.'
# Push the container image to artifact Registry
- id: push-tag
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - '--all-tags'
    - '${_IMAGE}'

substitutions:
    _IMAGE: europe-docker.pkg.dev/${PROJECT_ID}/images/valhalla
    _BUILDER_IMAGE: europe-docker.pkg.dev/${PROJECT_ID}/ghcr/valhalla/valhalla
options:
  logging: CLOUD_LOGGING_ONLY
